version: '3.8'

services:
  news-aggregator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_NEWS_API_KEY=${NEWS_API_KEY}
      - VITE_GUARDIAN_API_KEY=${GUARDIAN_API_KEY}
      - VITE_NYT_API_KEY=${NYT_API_KEY} 